// <auto-generated />
using Day02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923092743_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day02.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DepartmentId = 1,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            DepartmentId = 1,
                            Hours = 60,
                            MinDegree = 50,
                            Name = "C# Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            DepartmentId = 2,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Java Basics"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            DepartmentId = 2,
                            Hours = 60,
                            MinDegree = 50,
                            Name = "Java Advanced"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100,
                            DepartmentId = 3,
                            Hours = 40,
                            MinDegree = 50,
                            Name = "Python Basics"
                        },
                        new
                        {
                            Id = 6,
                            Degree = 100,
                            DepartmentId = 3,
                            Hours = 60,
                            MinDegree = 50,
                            Name = "Python Advanced"
                        });
                });

            modelBuilder.Entity("Day02.Models.CrsResult", b =>
                {
                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.HasKey("TraineeId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CrsResults");

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            CourseId = 1,
                            Degree = 80
                        },
                        new
                        {
                            TraineeId = 1,
                            CourseId = 2,
                            Degree = 70
                        },
                        new
                        {
                            TraineeId = 2,
                            CourseId = 3,
                            Degree = 90
                        },
                        new
                        {
                            TraineeId = 2,
                            CourseId = 4,
                            Degree = 85
                        },
                        new
                        {
                            TraineeId = 3,
                            CourseId = 5,
                            Degree = 95
                        },
                        new
                        {
                            TraineeId = 3,
                            CourseId = 6,
                            Degree = 80
                        },
                        new
                        {
                            TraineeId = 4,
                            CourseId = 1,
                            Degree = 60
                        },
                        new
                        {
                            TraineeId = 4,
                            CourseId = 2,
                            Degree = 75
                        },
                        new
                        {
                            TraineeId = 5,
                            CourseId = 3,
                            Degree = 88
                        },
                        new
                        {
                            TraineeId = 5,
                            CourseId = 4,
                            Degree = 92
                        });
                });

            modelBuilder.Entity("Day02.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Ahmed",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Mohamed",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Manager = "Omar",
                            Name = "Python"
                        });
                });

            modelBuilder.Entity("Day02.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            DepartmentId = 1,
                            ImageUrl = "1.png",
                            Name = "Ali",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            DepartmentId = 2,
                            ImageUrl = "1.png",
                            Name = "Hassan",
                            Salary = 12000
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 5,
                            DepartmentId = 3,
                            ImageUrl = "1.png",
                            Name = "Mahmoud",
                            Salary = 15000
                        });
                });

            modelBuilder.Entity("Day02.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            DepartmentId = 1,
                            ImageUrl = "1.png",
                            Name = "Taha"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            DepartmentId = 2,
                            ImageUrl = "2.png",
                            Name = "Youssef"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            DepartmentId = 3,
                            ImageUrl = "3.png",
                            Name = "Khaled"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            DepartmentId = 1,
                            ImageUrl = "4.png",
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Giza",
                            DepartmentId = 2,
                            ImageUrl = "5.png",
                            Name = "Salma"
                        });
                });

            modelBuilder.Entity("Day02.Models.Course", b =>
                {
                    b.HasOne("Day02.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day02.Models.CrsResult", b =>
                {
                    b.HasOne("Day02.Models.Course", "Course")
                        .WithMany("CrsResults")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day02.Models.Trainee", "Trainee")
                        .WithMany("CrsResults")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Day02.Models.Instructor", b =>
                {
                    b.HasOne("Day02.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day02.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day02.Models.Trainee", b =>
                {
                    b.HasOne("Day02.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day02.Models.Course", b =>
                {
                    b.Navigation("CrsResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Day02.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Day02.Models.Trainee", b =>
                {
                    b.Navigation("CrsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
